myMovieApp/force-app/main/default/objects/MovieActor__c/MovieActor__c.object-meta.xml
<CustomObject>
    <label>MovieActor</label>
    <nameField>
        <label>MovieActor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MovieActors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

myMovieApp/force-app/main/default/objects/MovieActor__c/fields/MD_to_Actors__c.field-meta.xml
<CustomField>
    <fullName>MD_to_Actors__c</fullName>
    <label>MD to Actors</label>
    <referenceTo>Actor__c</referenceTo>
    <relationshipLabel>MovieActors</relationshipLabel>
    <relationshipName>MovieActors</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

myMovieApp/force-app/main/default/objects/MovieActor__c/fields/MD_to_Movies__c.field-meta.xml
<CustomField>
    <fullName>MD_to_Movies__c</fullName>
    <label>MD to Movies</label>
    <referenceTo>Movie__c</referenceTo>
    <relationshipLabel>MovieActors</relationshipLabel>
    <relationshipName>MovieActors</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

myMovieApp/force-app/main/default/classes/MovieActorService.cls
public with sharing class MovieActorService {
    public static void addActorsToMovie(Id movieId, List<Id> actorIds) {
        if(actorIds !=null && !actorIds.isEmpty()){
            List<MovieActor__c> movieActors = new List<MovieActor__c>();
            for(Id actorId: actorIds){
                MovieActor__c movieActor = new MovieActor__c();
                movieActor.MD_to_Movies__c = movieId;
                movieActor.MD_to_Actors__c = actorId;
                movieActors.add(movieActor);
            }
            Database.SaveResult[] saveResults = Database.insert(movieActors, false);
            Log.error(saveResults); 
        }
    }

    
}